@HOST = http://localhost:8081
###
GET {{HOST}}/tokenz

###

POST {{HOST}}/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTAyNzIxOTF9.kyCEfiUaWeJsCx0dAPlBgbiIwzI64TH0fWGFGEczZeQ

{
    "text" : "test 1"
}

###
GET {{HOST}}/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTAyNzIxOTF9.kyCEfiUaWeJsCx0dAPlBgbiIwzI64TH0fWGFGEczZeQ