@HOST = http://localhost:8081
GET {{HOST}}/ping
###
GET {{HOST}}/tokenz

###

POST {{HOST}}/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTAwMzY1OTZ9.vcoKy-em8nQzwcaJ3TZ_0SoMPT4IbKDRJADtHf88lRg

{
    "text" : "test 6"
}

###
GET {{HOST}}/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTAwMzY1OTZ9.vcoKy-em8nQzwcaJ3TZ_0SoMPT4IbKDRJADtHf88lRg